[package]
name = "luna_ui"
version = "0.1.0"
edition = "2021"

[features]
dev = []
release = []
default = ["dev"]


[dependencies]
base64 = "0.22.1"
cargo_metadata = "0.20.0"
imghdr = "0.7.0"
makepad-widgets = { path = "/Users/shengyifei/projects/makepad/makepad/widgets" }
reqwest = { version = "0.12.22", features = ["blocking"] }
toml_edit = "0.22.26"
